execution:
- concurrency: 10
  hold-for: 1m
  ramp-up: 20s
  scenario: with_script
  
scenarios:
  with_script:
    script: testing.jmx

reporting:
- module: final-stats
- module: console

modules:
  jmeter:
    path: /usr/local/bin/jmeter
    properties:
        log_level: DEBUG
  console:
    disable: false
    
settings:
  check-interval: 5s
  default-executor: jmeter

provisioning: local